### ISSUE TITLE
Plugin not existing in Photoshop 2022

### ISSUE THREAD

**Issue by ogland** [tinify/photoshop-scripts#11]
As in the title. After installing and rebooting photoshop it simply doesn't exist as an option, despite being in the plug-ins folder with the license.

**Comment by rkoopmans** [comment]
Hi Ogland,

Could you reach out to support@tinify.com with the email you bought the license with? We need some additional information to investigate your issue. 
Please include your operating system and chip architecture in case of MacOS (in case you have a M1 chip).

**Comment by ogland** [comment]
> Hi Ogland,
> 
> Could you reach out to [support@tinify.com](mailto:support@tinify.com) with the email you bought the license with? We need some additional information to investigate your issue. Please include your operating system and chip architecture in case of MacOS (in case you have a M1 chip).

Hi, not possible to send an email from that adress since it's bought by my client.

I'm on a Ryzen 5 3600X in this case.

**Comment by rkoopmans** [comment]
Did your client try to reinstall the latest version of the plugin?

**Comment by ogland** [comment]
I did try the latest version of the plugin, just yesterday.

**Comment by rkoopmans** [comment]
Could you ask your client to contact support@tinify.com?

The team can assist through our support portal.

**Comment by ogland** [comment]
Why? I'm the one using the plugin.

**Comment by rkoopmans** [comment]
Sorry, I misunderstood you and thought it was your client having an issue. 

Could you reach out to support@tinify.com ?

please include the link to this github issue. On the support team we can loop in people with different hats to resolve your issue :)
