### ISSUE TITLE
Incorrect Path on macOS in the Readme.md

### ISSUE THREAD

**Issue by bjornskjaerpe** [tinify/photoshop-scripts#7]
You have this path in your documentation, which is wrong:

> Mac: /Applications/Adobe Photoshop (version)/Presets/Scripts/

The correct path is: **~/Library/Application Support/Adobe/Adobe Photoshop 2020/Presets/Scripts**

Where ~ is home folder of a user. The directory `Adobe Photoshop 2020` can be different, prior to 2020 the names were CC 2019, CC 2018, i.e. `Adobe Photoshop CC 2019`.

**Comment by bjornskjaerpe** [comment]
By the way the script doesn‘t work for me, but it‘s a different issue, I‘m trying to investigate what‘s wrong with it.

**Comment by mattijsvandruenen** [comment]
Thanks for the feedback! The path that is in the readme isn't necessarily incorrect though. The path you mentioned is a user specific folder, so it probably depends on whether you want to share the script with other users on the same Mac or not.

In any case, I've added it to the readme.
