### ISSUE TITLE
Error! Missing Or invalid Action name

### ISSUE THREAD

**Issue by faizandilbaz** [tinify/photoshop-scripts#9]
I'm getting this issue with erc20 (etherum) token API
I'm trying to use this API to get details against the address using my API key at the end

https://api.etherscan.io/api?module=token&action=tokeninfo&contractaddress=0x0e3a2a1f2146d86a604adc220b4967a898d7fe07&apikey=YourApiKeyToken

but I'm getting this error at the postman 

{
    "status": "0",
    "message": "NOTOK",
    "result": "Error! Missing Or invalid Action name"
}

**Comment by rolftimmermans** [comment]
Are you sure you posted this in the right repository?

**Comment by chokey2nv** [comment]
> Are you sure you posted this in the right repository?

I am also having this issue.

**Comment by Evertrotshuizen** [comment]
@chokey2nv the issue that @faizandilbaz reported is not related to this repository. This repo does not have anything to do with Ethereum. Im not exactly sure where the confusion came from but I will close this issue for now.
